[package]
name = "bevy_outline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
nanorand = "0.7.0"

[dev-dependencies]
bevy_mod_picking = "0.11.0"
